{
 "title": "Storj-Exporter-Logs",
 "tags": [
  "storj",
  "docker",
  "prometheus",
  "exporter",
  "loki",
  "promtail"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node:",
    "query": {
     "query": "label_values(storj_nodeID_info, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Combined summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (nodename) (storj_nodeID_info{nodename=~\"$node.*\"})) OR vector(0)",
     "legendFormat": "Nodes online"
    },
    {
     "expr": "count(count by (nodename) (storj_log_levels{nodename=~\"$node.*\"})) OR vector(0)",
     "legendFormat": "Logs watched"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_sat_month_ingress{instance=~\"$node.*\"})",
     "legendFormat": "MTD Ingress"
    },
    {
     "expr": "sum(storj_sat_month_egress{instance=~\"$node.*\"})",
     "legendFormat": "MTD Egress"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_total_diskspace{type=\"available\",instance=~\"$node.*\"})",
     "legendFormat": "Disk Allocated"
    },
    {
     "expr": "sum (storj_total_diskspace{type=\"used\",instance=~\"$node.*\"})",
     "legendFormat": "Disk Used"
    },
    {
     "expr": "sum (storj_total_diskspace{type=\"available\",instance=~\"$node.*\"}) - sum (storj_total_diskspace{type=\"used\",instance=~\"$node.*\"})",
     "legendFormat": "Disk Free"
    },
    {
     "expr": "sum (storj_total_diskspace{type=\"trash\",instance=~\"$node.*\"})",
     "legendFormat": "Disk Trash"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_payout_currentMonth{type=~\"payout|held\",instance=~\"$node.*\"}) / 100",
     "legendFormat": "MTD Earnings"
    },
    {
     "expr": "sum(storj_payout_currentMonth{type=~\"held\",instance=~\"$node.*\"})/100",
     "legendFormat": "MTD Held"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_pieces_upload_successful{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload successful"
    },
    {
     "expr": "sum(storj_pieces_upload_canceled{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload canceled"
    },
    {
     "expr": "sum(storj_pieces_upload_rejected{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload rejected"
    },
    {
     "expr": "sum(storj_pieces_download_successful{nodename=~\"$node.*\"})/sum(storj_pieces_download_started{nodename=~\"$node.*\"})",
     "legendFormat": "Download successful"
    },
    {
     "expr": "sum(storj_pieces_download_canceled{nodename=~\"$node.*\"})/sum(storj_pieces_download_started{nodename=~\"$node.*\"})",
     "legendFormat": "Download canceled"
    },
    {
     "expr": "sum(storj_pieces_delete_successful{nodename=~\"$node.*\"})/(sum(storj_pieces_delete_successful{nodename=~\"$node.*\"})+sum(storj_pieces_delete_failed{nodename=~\"$node.*\"} OR vector(0)))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Ingress rate"
    },
    {
     "expr": "sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Egress rate"
    },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Delete rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(min(storj_sat_audit{type=\"onlineScore\", nodename=~\"$node.*\"}*10000))/10000",
     "legendFormat": "Min Uptime"
    },
    {
     "expr": "floor(min(storj_sat_audit{type=~\"unknownScore|suspensionScore\",nodename=~\"$node.*\"}*10000))/10000",
     "legendFormat": "Min Suspension"
    },
    {
     "expr": "floor(min(storj_sat_audit{type=~\"score|auditScore\", nodename=~\"$node.*\"}*10000))/10000",
     "legendFormat": "Min Audit"
    }
   ]
  },
  {
   "title": "Log Level Counts (within time range)",
   "type": "stat",
   "description": "Number of changes in log entries of the different log levels. (Errors will disappear e.g. shown as 0 if there are no new messages within the chosen timeframe)\nError Count excludes falsely classified errors (e.g. shutdown of runner, download/upload failed due to client side errors, graceful exit errors if you GE'ed on stefan-benten).",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"INFO\"})",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"WARN\"}) OR vector(0)",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(storj_log_errors_corr{nodename=~\"$node.*\",loglevel=\"ERROR\"}) OR vector(0)",
     "legendFormat": "Error (cor.)"
    },
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"FATAL\"})  OR vector(0)",
     "legendFormat": "Fatal"
    }
   ]
  },
  {
   "title": "Node IO",
   "type": "stat",
   "description": "Number of changes in log entries of the different log levels. (Errors will disappear e.g. shown as 0 if there are no new messages within the chosen timeframe)\nError Count excludes falsely classified errors (e.g. shutdown of runner, download/upload failed due to client side errors, graceful exit errors if you GE'ed on stefan-benten).",
   "gridPos": { "h": 4, "w": 9, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[$__rate_interval])) * 8",
     "legendFormat": "Ingress Rate"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[$__rate_interval])) * 8",
     "legendFormat": "Egress Rate"
    },
    {
     "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) *8 / 300",
     "legendFormat": "Disk Usage Rate"
    }
   ]
  },
  {
   "title": "Average Piece Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m]))",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[5m]))",
     "legendFormat": "Egress"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "ERROR (cor.) and FATAL Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"storj\",loglevel=\"FATAL\",nodename=~\"$node.*\"}"
    },
    {
     "expr": "{job=\"storj\",loglevel=\"ERROR\",nodename=~\"$node.*\", errorCorrected=\"corrected\"}"
    }
   ]
  },
  { "title": "Node overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Node summary table",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* DQ - Disqualified\n* SU - Suspended\n* UTD - Up to date",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(storj_sat_month_ingress{nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | In"
    },
    {
     "expr": "sum(storj_sat_month_egress{nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Out"
    },
    {
     "expr": "sum(storj_sat_month_egress{type=\"repair\",nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Repair"
    },
    {
     "expr": "sum(storj_total_diskspace{type=\"available\", nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Disk available"
    },
    {
     "expr": "sum(storj_total_diskspace{type=\"used\", nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Disk used"
    },
    {
     "expr": "sum (storj_total_diskspace{type=\"available\",nodename=~\"$node.*\"}) by(nodename) - sum (storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Free"
    },
    {
     "expr": "sum(storj_total_diskspace{type=\"trash\", nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Trash"
    },
    {
     "expr": "sum(storj_payout_currentMonth{type=~\"payout|held\",nodename=~\"$node.*\"}) by (nodename) / 100",
     "legendFormat": "{{nodename}} | Earnings"
    },
    {
     "expr": "sum(storj_payout_currentMonth{type=~\"held\",nodename=~\"$node.*\"}) by (nodename) / 100",
     "legendFormat": "{{nodename}} | Held"
    },
    {
     "expr": "floor(avg(storj_sat_summary{type=\"onlineScore\", nodename=~\"$node.*\"} or storj_sat_audit{type=\"onlineScore\", nodename=~\"$node.*\"}) by(nodename) * 10000) / 100",
     "legendFormat": "{{nodename}} | Uptime"
    },
    {
     "expr": "floor(avg(storj_sat_audit{type=~\"score|auditScore\", nodename=~\"$node.*\"}) by(nodename) * 10000) / 100",
     "legendFormat": "{{nodename}} | Audit"
    },
    {
     "expr": "avg (storj_sat_summary{type=\"disqualified\",nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Disqualified"
    },
    {
     "expr": "floor(avg(storj_sat_audit{type=~\"unknownScore|suspensionScore\",nodename=~\"$node.*\"}) by(nodename) * 10000) / 100",
     "legendFormat": "{{nodename}} | Suspension"
    },
    {
     "expr": "avg (storj_sat_summary{type=\"suspended\",nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "{{nodename}} | Suspended"
    },
    {
     "expr": "storj_node_info{version!=\"\",nodename=~\"$node.*\"}",
     "legendFormat": "{{nodename}} | Version | {{version}}"
    },
    {
     "expr": "avg (storj_upToDate_info{nodename=~\"$node.*\"}) by (nodename)",
     "legendFormat": "{{nodename}} | UpToDate"
    }
   ]
  },
  { "title": "Node IO simple", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk Usage rate by node (stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bps", "label": "Storage IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) by(nodename) * 8 / 300",
     "legendFormat": "DiskRate {{nodename}}"
    }
   ]
  },
  {
   "title": "Ingress/Egress rate by node (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateIn {{nodename}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateOut {{nodename}}"
    }
   ]
  },
  {
   "title": "Piece Ingress/Egress rate (stacked)",
   "type": "graph",
   "description": "Pieces per second",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) ",
     "legendFormat": "RateOut {{nodename}}"
    },
    {
     "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "RateIn {{nodename}}"
    },
    { "expr": "0", "legendFormat": "0" },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "RateDelete {{nodename}}"
    }
   ]
  },
  {
   "title": "Usage Ingress/Egress rate by node (stacked)",
   "type": "graph",
   "description": "Normal Ingress and Egress without Repair Traffic and Audits",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateIn {{nodename}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateOut {{nodename}}"
    }
   ]
  },
  {
   "title": "Repair Ingress/Egress rate by node (stacked)",
   "type": "graph",
   "description": "Audit and Repair not separated because Audit is almost irrelevant in comparison.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bps", "label": "Rate Out (-) / Rate In (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RepairIn {{nodename}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RepairOut {{nodename}}"
    }
   ]
  },
  {
   "title": "Node IO by node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Usage rate by node (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bps", "label": "Storage IO rate" }
     ],
     "targets": [
      {
       "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) by(nodename) * 8 / 300",
       "legendFormat": "DiskRate {{nodename}}"
      }
     ]
    },
    {
     "title": "Ingress/Egress rate by node (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateIn {{nodename}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateOut {{nodename}}"
      }
     ]
    },
    {
     "title": "Piece Ingress/Egress rate (stacked)",
     "type": "graph",
     "description": "Pieces per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(nodename)",
       "legendFormat": "RateOut {{nodename}}"
      },
      {
       "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(nodename)",
       "legendFormat": "RateIn {{nodename}}"
      },
      { "expr": "0", "legendFormat": "0" },
      {
       "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(nodename)",
       "legendFormat": "RateDelete {{nodename}}"
      }
     ]
    },
    {
     "title": "Usage Ingress/Egress rate by node (stacked)",
     "type": "graph",
     "description": "Normal Ingress and Egress without Repair Traffic and Audits",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateIn {{nodename}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateOut {{nodename}}"
      }
     ]
    },
    {
     "title": "Repair Ingress/Egress rate by node (stacked)",
     "type": "graph",
     "description": "Audit and Repair not separated because Audit is almost irrelevant in comparison.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "bps", "label": "Rate Out (-) / Rate In (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RepairIn {{nodename}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RepairOut {{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node IO by satellite",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Piece rate by Satellite (stacked)",
     "type": "graph",
     "description": "Pieces per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "RateOut {{url}}"
      },
      {
       "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "RateIn {{url}}"
      },
      { "expr": "0", "legendFormat": "0" },
      {
       "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "RateDelete {{url}}"
      }
     ]
    },
    {
     "title": "Ingress/Egress rate by Satellite (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(url) * 8",
       "legendFormat": "RateIn {{url}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(url) * 8",
       "legendFormat": "RateOut {{url}}"
      }
     ]
    },
    {
     "title": "Usage Ingress/Egress rate by Satellite (stacked)",
     "type": "graph",
     "description": "Normal Ingress and Egress without Repair Traffic and Audits",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(url) * 8",
       "legendFormat": "RateIn {{url}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(url) * 8",
       "legendFormat": "RateOut {{url}}"
      }
     ]
    },
    {
     "title": "Repair Ingress/Egress rate by Satellite (stacked)",
     "type": "graph",
     "description": "Audit and Repair not separated because Audit is almost irrelevant in comparison.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
     "yaxes": [
      { "format": "bps", "label": "Rate Out (-) / Rate In (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(url) * 8",
       "legendFormat": "RepairIn {{url}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(url) * 8",
       "legendFormat": "RepairOut {{url}}"
      }
     ]
    }
   ]
  },
  { "title": "Successrates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Successrate Upload by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(storj_pieces_upload_successful{nodename=~\"$node.*\"}) by(nodename)/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "Upload {{nodename}}"
    },
    {
     "expr": "sum(storj_pieces_upload_successful{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"})",
     "legendFormat": "Upload average"
    }
   ]
  },
  {
   "title": "Successrate Download by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(storj_pieces_download_successful{nodename=~\"$node.*\"}) by(nodename)/sum(storj_pieces_download_started{nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "Download {{nodename}}"
    },
    {
     "expr": "sum(storj_pieces_download_successful{nodename=~\"$node.*\"})/sum(storj_pieces_download_started{nodename=~\"$node.*\"})",
     "legendFormat": "Download average"
    }
   ]
  },
  {
   "title": "Piece Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Piece Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m]))",
       "legendFormat": "Ingress"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[5m]))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\",type=\"usage\"}[5m]))",
       "legendFormat": "Ingress"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\",type=\"usage\"}[5m]))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size Repair",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"repair\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\",type=\"repair\"}[5m]))",
       "legendFormat": "Ingress"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"repair\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\",type=\"repair\"}[5m]))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m])) ",
       "legendFormat": "Ingress"
      },
      {
       "expr": "(sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[5m])))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size (by type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(type)/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m])) by(type)",
       "legendFormat": "Ingress {{type}}"
      },
      {
       "expr": "(sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(type)/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\",type!=\"audit\"}[5m])) by(type))",
       "legendFormat": "Egress {{type}}"
      }
     ]
    }
   ]
  },
  { "title": "$node details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }, "repeat": "node" },
  {
   "title": "$node Satellite summary table (monthly)",
   "type": "yesoreyeram-boomtable-panel",
   "description": "* DQ - Disqualified\n* SU - Suspended\n* UTD - Up to date",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(storj_sat_month_ingress{nodename=~\"$node.*\"}) by(url)",
     "legendFormat": "{{url}} | In"
    },
    {
     "expr": "sum(storj_sat_month_egress{nodename=~\"$node.*\"}) by(url)",
     "legendFormat": "{{url}} | Out"
    },
    {
     "expr": "(sum(storj_sat_summary{type=\"storageSummary\",nodename=~\"$node.*\"}) by(url) / (30 * 24) * 1.5  / 1000^4) + (sum(storj_sat_month_egress{nodename=~\"$node.*\"}) by(url) / 1000^4 * 20)",
     "legendFormat": "{{url}} | Payout"
    },
    {
     "expr": "sum(storj_sat_audit{type=\"successCount\",nodename=~\"$node.*\"}) by (url)",
     "legendFormat": "{{url}} | Vetting"
    },
    {
     "expr": "avg(storj_sat_summary{type=\"onlineScore\", nodename=~\"$node.*\"}) by(url) * 100",
     "legendFormat": "{{url}} | Uptime"
    },
    {
     "expr": "avg(storj_sat_audit{type=\"score\",nodename=~\"$node.*\"}) by(url) * 100",
     "legendFormat": "{{url}} | Audit"
    },
    {
     "expr": "sum(storj_sat_summary{type=\"disqualified\",nodename=~\"$node.*\"}) by (url)",
     "legendFormat": "{{url}} | Disqualified"
    },
    {
     "expr": "sum(storj_sat_summary{type=\"suspended\",nodename=~\"$node.*\"}) by (url)",
     "legendFormat": "{{url}} | Suspended"
    }
   ]
  },
  {
   "title": "Disk Usage rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bps", "label": "Storage IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) by(nodename) * 8 / 300",
     "legendFormat": "DiskRate {{nodename}}"
    }
   ]
  },
  {
   "title": "Ingress/Egress rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateIn {{nodename}}"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateOut {{nodename}}"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of upload messages",
     "type": "graph",
     "description": "This should be around -20<0<20. Theoretically it should be 0 if all uploads successful/canceled/failed/rejected are summed up but restarting the exporter can miss a few messages.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum(storj_pieces_upload_started{nodename=~\"$node.*\"})) - (sum(storj_pieces_upload_successful{nodename=~\"$node.*\"})) - (sum(storj_pieces_upload_canceled{nodename=~\"$node.*\"})) OR vector(0) - (sum(storj_pieces_upload_failed{nodename=~\"$node.*\"})) OR vector(0) - (sum(storj_pieces_upload_rejected{nodename=~\"$node.*\"})) OR vector(0)",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Sum of download messages",
     "type": "graph",
     "description": "This should be around -20<0<20. Theoretically it should be 0 if all download successful/canceled/failed are summed up but restarting the exporter can miss a few messages.",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(storj_pieces_download_started{nodename=~\"$node.*\"}) - sum(storj_pieces_download_successful{nodename=~\"$node.*\"}) - (sum(storj_pieces_download_canceled{nodename=~\"$node.*\"}) or vector(0)) - (sum(storj_pieces_download_failed{nodename=~\"$node.*\"}) or vector(0))",
       "legendFormat": "Sum Download messages"
      }
     ]
    },
    {
     "title": "Errors Debug",
     "type": "stat",
     "description": "Missing Error messages in storj_log_errors filter. If this is >0, please send me your error logs.",
     "gridPos": { "h": 6, "w": 2, "x": 10, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"ERROR\"})-sum(storj_log_errors{nodename=~\"$node.*\",loglevel=\"ERROR\"})",
       "legendFormat": "Errors per minute"
      }
     ]
    },
    {
     "title": "Payout per Satellite",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(storj_sat_month_egress{type=\"usage\",nodename=~\"$node.*\"}) by(url) /1000000000000*20 + sum(storj_sat_month_egress{type=\"repair\",nodename=~\"$node.*\"}) by(url)/1000000000000*10 + sum(storj_sat_summary{nodename=~\"$node.*\",type=\"storageSummary\"}) by(url) /720/1000000000000*1.5",
       "legendFormat": "Payout {{url}}"
      }
     ]
    },
    {
     "title": "Average Piece Size (per satellite)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 230 },
     "yaxes": [
      { "format": "decbytes", "label": "Sum-out (-) / Sum-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[$__rate_interval])) by(url) / sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "IngressPieceSize-{{url}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[$__rate_interval])) by(url) / sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "EgressPieceSize-{{url}}"
      }
     ]
    },
    {
     "title": "Cumulative Errors (Corr) by Node (since Promtail restart)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(storj_log_errors_corr{nodename=~\"$node.*\"}) by (nodename,message) OR vector (0)",
       "legendFormat": "Errors {{nodename}}: {{message}}"
      },
      {
       "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"FATAL\"}) by(nodename,message) OR vector(0)",
       "legendFormat": "Fatal {{nodename}}: {{message}}"
      }
     ]
    },
    {
     "title": "Joined satellite (single node) - debug",
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 236 },
     "targets": [
      {
       "expr": "storj_sat_nodeJoinedAt_info{nodeJoinedAt!=\"\",nodename=~\"$node\"}",
       "legendFormat": "{{url}} | JoinedAt | {{nodeJoinedAt}}"
      }
     ]
    }
   ]
  }
 ]
}