{
 "title": "Storj-Exporter-Promtail",
 "tags": [
  "storj",
  "docker",
  "prometheus",
  "exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node:",
    "query": "label_values(storj_nodeID_info, nodename)"
   }
  ]
 },
 "panels": [
  { "title": "Combined summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (nodename) (storj_nodeID_info{nodename=~\"$node.*\"})) OR vector(0)",
     "legendFormat": "Nodes online"
    },
    {
     "expr": "count(count by (nodename) (storj_log_levels{nodename=~\"$node.*\"})) OR vector(0)",
     "legendFormat": "Logs watched"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_sat_month_ingress{nodename=~\"$node.*\"})",
     "legendFormat": "Ingress Month"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_sat_month_egress{nodename=~\"$node.*\"})",
     "legendFormat": "Egress Month"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_total_diskspace{type=\"available\",nodename=~\"$node.*\"})",
     "legendFormat": "Disk Allocated"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (storj_total_diskspace{type=\"trash\",nodename=~\"$node.*\"})",
     "legendFormat": "Disk Trash"
    }
   ]
  },
  {
   "title": "Successrates",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_pieces_upload_successful{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(storj_pieces_upload_canceled{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload canceled"
    },
    {
     "expr": "sum(storj_pieces_upload_rejected{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) or vector(0)",
     "legendFormat": "Upload rejected"
    },
    {
     "expr": "sum(storj_pieces_download_successful{nodename=~\"$node.*\"})/sum(storj_pieces_download_started{nodename=~\"$node.*\"})",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(storj_pieces_download_canceled{nodename=~\"$node.*\"})/sum(storj_pieces_download_started{nodename=~\"$node.*\"})",
     "legendFormat": "Download canceled"
    },
    {
     "expr": "sum(storj_pieces_delete_successful{nodename=~\"$node.*\"})/(sum(storj_pieces_delete_successful{nodename=~\"$node.*\"})+sum(storj_pieces_delete_failed{nodename=~\"$node.*\"} OR vector(0)))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Net IO average (pieces per second)",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Net in (avg)"
    },
    {
     "expr": "sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Net out (avg)"
    },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
     "legendFormat": "Net delete (avg)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_payout_currentMonth{type=~\"payout|held\",nodename=~\"$node.*\"}) / 100",
     "legendFormat": "Earnings Month"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storj_payout_currentMonth{type=~\"held\",nodename=~\"$node.*\"})/100",
     "legendFormat": "Held back"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"})",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (storj_total_diskspace{type=\"available\",nodename=~\"$node.*\"}) - sum (storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"})",
     "legendFormat": "Disk Free"
    }
   ]
  },
  {
   "title": "Min Uptime",
   "type": "stat",
   "description": "Minimum Uptime Score of all nodes on any satellite",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(storj_sat_summary{type=\"onlineScore\", nodename=~\"$node.*\"})",
     "legendFormat": "Min Uptime"
    }
   ]
  },
  {
   "title": "Min Audit",
   "type": "stat",
   "description": "Minimum Audit Score of all nodes on any satellite",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(storj_sat_audit{type=\"score\", nodename=~\"$node.*\"})",
     "legendFormat": "Min Audit"
    }
   ]
  },
  {
   "title": "Min Suspension",
   "type": "stat",
   "description": "Minimum Suspension Score of all nodes on any satellite",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(storj_sat_audit{type=\"unknownScore\"})",
     "legendFormat": "Min Suspension"
    }
   ]
  },
  {
   "title": "Log Entries (within time range)",
   "type": "stat",
   "description": "Number of changes in log entries of the different log levels. (Errors will disappear e.g. shown as 0 if there are no new messages within the chosen timeframe)\nError Count excludes falsely classified errors (e.g. shutdown of runner, download/upload failed due to client side errors, graceful exit errors if you GE'ed on stefan-benten).",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"INFO\"})",
     "legendFormat": "Info"
    },
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"WARN\"}) OR vector(0)",
     "legendFormat": "Warn"
    },
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"ERROR\"})-(sum(storj_log_errors{nodename=~\"$node.*\",type=\"gracefulexit:service\\tfailed to get satellite address\"}) OR vector(0)) - (sum(storj_log_errors{nodename=~\"$node.*\",type=\"piecestore\\tdownload failed\"}) OR vector(0)) - (sum(storj_log_errors{nodename=~\"$node.*\",type=\"piecestore\\tupload failed\"}) OR vector(0)) -  (sum(storj_log_errors{nodename=~\"$node.*\",type=\"servers\\tunexpected shutdown of a runner\"}) OR vector(0)) OR vector(0)",
     "legendFormat": "Error (cor.)"
    },
    {
     "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"FATAL\"})  OR vector(0)",
     "legendFormat": "Fatal"
    }
   ]
  },
  {
   "title": "Average Piece Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m]))",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[5m]))",
     "legendFormat": "Egress"
    }
   ]
  },
  {
   "title": "Node overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node summary table",
     "type": "yesoreyeram-boomtable-panel",
     "description": "* DQ - Disqualified\n* SU - Suspended\n* UTD - Up to date",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(storj_sat_month_ingress{nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | In"
      },
      {
       "expr": "sum(storj_sat_month_egress{nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Out"
      },
      {
       "expr": "sum(storj_sat_month_egress{type=\"repair\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Repair"
      },
      {
       "expr": "sum(storj_total_diskspace{type=\"available\", nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Disk available"
      },
      {
       "expr": "sum(storj_total_diskspace{type=\"used\", nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Disk used"
      },
      {
       "expr": "sum (storj_total_diskspace{type=\"available\",nodename=~\"$node.*\"}) by(nodename) - sum (storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Free"
      },
      {
       "expr": "sum(storj_total_diskspace{type=\"trash\", nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Trash"
      },
      {
       "expr": "sum(storj_payout_currentMonth{type=~\"payout|held\",nodename=~\"$node.*\"}) by (nodename) / 100",
       "legendFormat": "{{nodename}} | Earnings"
      },
      {
       "expr": "sum(storj_payout_currentMonth{type=~\"held\",nodename=~\"$node.*\"}) by (nodename) / 100",
       "legendFormat": "{{nodename}} | Held"
      },
      {
       "expr": "avg(storj_sat_summary{type=\"onlineScore\", nodename=~\"$node.*\"}) by(nodename) * 100",
       "legendFormat": "{{nodename}} | Uptime"
      },
      {
       "expr": "avg(storj_sat_audit{type=\"score\", nodename=~\"$node.*\"}) by(nodename) * 100",
       "legendFormat": "{{nodename}} | Audit"
      },
      {
       "expr": "avg (storj_sat_summary{type=\"disqualified\",nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Disqualified"
      },
      {
       "expr": "avg(storj_sat_audit{type=\"unknownScore\"}) by(nodename) * 100",
       "legendFormat": "{{nodename}} | Suspension"
      },
      {
       "expr": "avg (storj_sat_summary{type=\"suspended\",nodename=~\"$node.*\"}) by(nodename)",
       "legendFormat": "{{nodename}} | Suspended"
      },
      {
       "expr": "storj_node_info{version!=\"\",nodename=~\"$node.*\"}",
       "legendFormat": "{{nodename}} | Version | {{version}}"
      },
      {
       "expr": "avg (storj_upToDate_info{nodename=~\"$node.*\"}) by (nodename)",
       "legendFormat": "{{nodename}} | UpToDate"
      }
     ]
    }
   ]
  },
  {
   "title": "Net IO simple",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "StorageIO by node (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bps", "label": "Storage IO rate" }
     ],
     "targets": [
      {
       "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) by(nodename) * 8 / 300",
       "legendFormat": "DiskRate {{nodename}}"
      }
     ]
    },
    {
     "title": "NetIO by node (stacked)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateIn {{nodename}}"
      },
      {
       "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateOut {{nodename}}"
      }
     ]
    },
    {
     "title": "Net IO (stacked)",
     "type": "graph",
     "description": "Pieces per second",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "-sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) ",
       "legendFormat": "RateOut {{nodename}}"
      },
      {
       "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
       "legendFormat": "RateIn {{nodename}}"
      },
      { "expr": "0", "legendFormat": "0" },
      {
       "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval]))",
       "legendFormat": "RateDelete {{nodename}}"
      }
     ]
    },
    {
     "title": "Net IO Usage by node (stacked)",
     "type": "graph",
     "description": "Normal Ingress and Egress without Repair Traffic and Audits",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateIn {{nodename}}"
      },
      {
       "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateOut {{nodename}}"
      }
     ]
    },
    {
     "title": "Net IO Repair by node (stacked)",
     "type": "graph",
     "description": "Audit and Repair not separated because Audit is almost irrelevant in comparison.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bps", "label": "Rate Out (-) / Rate In (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RepairIn {{nodename}}"
      },
      {
       "expr": "-sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(nodename) * 8",
       "legendFormat": "RepairOut {{nodename}}"
      }
     ]
    }
   ]
  },
  { "title": "Net IO by node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "StorageIO by node (stacked)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bps", "label": "Storage IO rate" }
   ],
   "targets": [
    {
     "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) by(nodename) * 8 / 300",
     "legendFormat": "DiskRate {{nodename}}"
    }
   ]
  },
  {
   "title": "NetIO by node (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateIn {{nodename}}"
    },
    {
     "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateOut {{nodename}}"
    }
   ]
  },
  {
   "title": "Net IO by node (stacked)",
   "type": "graph",
   "description": "Pieces per second",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(nodename)",
     "legendFormat": "RateOut {{nodename}}"
    },
    {
     "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(nodename)",
     "legendFormat": "RateIn {{nodename}}"
    },
    { "expr": "0", "legendFormat": "0" },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(nodename)",
     "legendFormat": "RateDelete {{nodename}}"
    }
   ]
  },
  {
   "title": "Net IO Usage by node (stacked)",
   "type": "graph",
   "description": "Normal Ingress and Egress without Repair Traffic and Audits",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateIn {{nodename}}"
    },
    {
     "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RateOut {{nodename}}"
    }
   ]
  },
  {
   "title": "Net IO Repair by node (stacked)",
   "type": "graph",
   "description": "Audit and Repair not separated because Audit is almost irrelevant in comparison.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bps", "label": "Rate Out (-) / Rate In (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RepairIn {{nodename}}"
    },
    {
     "expr": "-sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(nodename) * 8",
     "legendFormat": "RepairOut {{nodename}}"
    }
   ]
  },
  { "title": "Net IO by satellite", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Net IO by Satellite (stacked)",
   "type": "graph",
   "description": "Pieces per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "RateOut {{url}}"
    },
    {
     "expr": "sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "RateIn {{url}}"
    },
    { "expr": "0", "legendFormat": "0" },
    {
     "expr": "sum(rate(storj_pieces_delete_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
     "legendFormat": "RateDelete {{url}}"
    }
   ]
  },
  {
   "title": "NetIO by Satellite (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(url) * 8",
     "legendFormat": "RateIn {{url}}"
    },
    {
     "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(url) * 8",
     "legendFormat": "RateOut {{url}}"
    }
   ]
  },
  {
   "title": "Net IO Usage by Satellite (stacked)",
   "type": "graph",
   "description": "Normal Ingress and Egress without Repair Traffic and Audits",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(url) * 8",
     "legendFormat": "RateIn {{url}}"
    },
    {
     "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m])) by(url) * 8",
     "legendFormat": "RateOut {{url}}"
    }
   ]
  },
  {
   "title": "NetIO Repair by Satellite (stacked)",
   "type": "graph",
   "description": "Audit and Repair not separated because Audit is almost irrelevant in comparison.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "bps", "label": "Rate Out (-) / Rate In (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(storj_sat_month_ingress{type!=\"usage\"}[5m])) by(url) * 8",
     "legendFormat": "RepairIn {{url}}"
    },
    {
     "expr": "-sum(rate(storj_sat_month_egress{type!=\"usage\"}[5m])) by(url) * 8",
     "legendFormat": "RepairOut {{url}}"
    }
   ]
  },
  { "title": "Successrates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Successrate Upload by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(storj_pieces_upload_successful{nodename=~\"$node.*\"}) by(nodename)/sum(storj_pieces_upload_started{nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "Upload {{nodename}}"
    },
    {
     "expr": "sum(storj_pieces_upload_successful{nodename=~\"$node.*\"})/sum(storj_pieces_upload_started{nodename=~\"$node.*\"})",
     "legendFormat": "Upload average"
    }
   ]
  },
  {
   "title": "Successrate Download by node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(storj_pieces_download_successful{nodename=~\"$node.*\"}) by(nodename)/sum(storj_pieces_download_started{nodename=~\"$node.*\"}) by(nodename)",
     "legendFormat": "Download {{nodename}}"
    },
    {
     "expr": "sum(storj_pieces_download_successful{nodename=~\"$node.*\"})/sum(storj_pieces_download_started{nodename=~\"$node.*\"})",
     "legendFormat": "Download average"
    }
   ]
  },
  {
   "title": "Piece Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Piece Size",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m]))",
       "legendFormat": "Ingress"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[5m]))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size Usage",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"usage\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\",type=\"usage\"}[5m]))",
       "legendFormat": "Ingress"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"usage\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\",type=\"usage\"}[5m]))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size Repair",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\",type=\"repair\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\",type=\"repair\"}[5m]))",
       "legendFormat": "Ingress"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\",type=\"repair\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\",type=\"repair\"}[5m]))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m])) ",
       "legendFormat": "Ingress"
      },
      {
       "expr": "-(sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m]))/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[5m])))",
       "legendFormat": "Egress"
      }
     ]
    },
    {
     "title": "Average Piece Size (by type)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(type)/sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[5m])) by(type)",
       "legendFormat": "Ingress {{type}}"
      },
      {
       "expr": "-(sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(type)/sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\",type!=\"audit\"}[5m])) by(type))",
       "legendFormat": "Egress {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$node details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "repeat": "node",
   "collapsed": true,
   "panels": [
    {
     "title": "$node Satellite summary table (monthly)",
     "type": "yesoreyeram-boomtable-panel",
     "description": "* DQ - Disqualified\n* SU - Suspended\n* UTD - Up to date",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "sum(storj_sat_month_ingress{nodename=~\"$node.*\"}) by(url)",
       "legendFormat": "{{url}} | In"
      },
      {
       "expr": "sum(storj_sat_month_egress{nodename=~\"$node.*\"}) by(url)",
       "legendFormat": "{{url}} | Out"
      },
      {
       "expr": "(sum(storj_sat_summary{type=\"storageSummary\",nodename=~\"$node.*\"}) by(url) / (30 * 24) * 1.5  / 1000^4) + (sum(storj_sat_month_egress{nodename=~\"$node.*\"}) by(url) / 1000^4 * 20)",
       "legendFormat": "{{url}} | Payout"
      },
      {
       "expr": "sum(storj_sat_audit{type=\"successCount\",nodename=~\"$node.*\"}) by (url)",
       "legendFormat": "{{url}} | Vetting"
      },
      {
       "expr": "avg(storj_sat_summary{type=\"onlineScore\", nodename=~\"$node.*\"}) by(url) * 100",
       "legendFormat": "{{url}} | Uptime"
      },
      {
       "expr": "avg(storj_sat_audit{type=\"score\",nodename=~\"$node.*\"}) by(url) * 100",
       "legendFormat": "{{url}} | Audit"
      },
      {
       "expr": "sum(storj_sat_summary{type=\"disqualified\",nodename=~\"$node.*\"}) by (url)",
       "legendFormat": "{{url}} | Disqualified"
      },
      {
       "expr": "sum(storj_sat_summary{type=\"suspended\",nodename=~\"$node.*\"}) by (url)",
       "legendFormat": "{{url}} | Suspended"
      }
     ]
    },
    {
     "title": "StorageIO by node (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bps", "label": "Storage IO rate" }
     ],
     "targets": [
      {
       "expr": "sum(delta(storj_total_diskspace{type=\"used\",nodename=~\"$node.*\"}[5m])) by(nodename) * 8 / 300",
       "legendFormat": "DiskRate {{nodename}}"
      }
     ]
    },
    {
     "title": "NetIO by node (stacked)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "bps", "label": "Rate-out (-) / Rate-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateIn {{nodename}}"
      },
      {
       "expr": "-sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[5m])) by(nodename) * 8",
       "legendFormat": "RateOut {{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of upload messages",
     "type": "graph",
     "description": "This should be around -20<0<20. Theoretically it should be 0 if all uploads successful/canceled/failed/rejected are summed up but restarting the exporter can miss a few messages.",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(storj_pieces_upload_started)-sum(storj_pieces_upload_successful)-(sum(storj_pieces_upload_canceled) or vector(0))-(sum(storj_pieces_upload_failed) or vector(0))-(sum(storj_pieces_upload_rejected) or vector(0))",
       "legendFormat": "Sum Upload messages"
      }
     ]
    },
    {
     "title": "Sum of download messages",
     "type": "graph",
     "description": "This should be around -20<0<20. Theoretically it should be 0 if all download successful/canceled/failed are summed up but restarting the exporter can miss a few messages.",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(storj_pieces_download_started)-sum(storj_pieces_download_successful)-(sum(storj_pieces_download_canceled) or vector(0))-(sum(storj_pieces_download_failed) or vector(0))",
       "legendFormat": "Sum Download messages"
      }
     ]
    },
    {
     "title": "Errors Debug",
     "type": "stat",
     "description": "Missing Error messages in storj_log_errors filter. If this is >0, please send me your error logs.",
     "gridPos": { "h": 4, "w": 2, "x": 10, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"ERROR\"})-sum(storj_log_errors{nodename=~\"$node.*\",loglevel=\"ERROR\"})",
       "legendFormat": "Errors per minute"
      }
     ]
    },
    {
     "title": "Payout per Satellite",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "yaxes": [
      { "format": "currencyUSD" }
     ],
     "targets": [
      {
       "expr": "sum(storj_sat_month_egress{type=\"usage\",nodename=~\"$node.*\"}) by(url) /1000000000000*20 + sum(storj_sat_month_egress{type=\"repair\",nodename=~\"$node.*\"}) by(url)/1000000000000*10 + sum(storj_sat_summary{nodename=~\"$node.*\",type=\"storageSummary\"}) by(url) /720/1000000000000*1.5",
       "legendFormat": "Payout {{url}}"
      }
     ]
    },
    {
     "title": "Average Piece Size (per satellite)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "decbytes", "label": "Sum-out (-) / Sum-in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(storj_sat_month_ingress{nodename=~\"$node.*\"}[$__rate_interval])) by(url) / sum(rate(storj_pieces_upload_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "IngressPieceSize-{{url}}"
      },
      {
       "expr": "sum(rate(storj_sat_month_egress{nodename=~\"$node.*\"}[$__rate_interval])) by(url) / sum(rate(storj_pieces_download_successful{nodename=~\"$node.*\"}[$__rate_interval])) by(url)",
       "legendFormat": "EgressPieceSize-{{url}}"
      }
     ]
    },
    {
     "title": "Errors by node (since exporter restart)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(storj_log_errors{nodename=~\"$node.*\",type!=\"gracefulexit:service\\tfailed to get satellite address\",type!=\"piecestore\\tdownload failed\",type!=\"piecestore\\tupload failed\",type!=\"servers\\tunexpected shutdown of a runner\"}) by(nodename,type) OR vector(0)",
       "legendFormat": "Errors {{nodename}}: {{type}}"
      },
      {
       "expr": "sum(storj_log_levels{nodename=~\"$node.*\",loglevel=\"FATAL\"}) by(nodename,type) OR vector(0)",
       "legendFormat": "Fatal {{nodename}}: {{type}}"
      }
     ]
    },
    {
     "title": "Joined satellite (single node) - debug",
     "type": "yesoreyeram-boomtable-panel",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "storj_sat_nodeJoinedAt_info{type=\"nodeJoinedAt\",nodeJoinedAt!=\"\",nodename=~\"$node\"}",
       "legendFormat": "{{url}} | JoinedAt | {{nodeJoinedAt}}"
      }
     ]
    }
   ]
  }
 ]
}