version: "3.8"
services:

  promtail:
    image: grafana/promtail:2.1.0
    ports:
      - "9080:9080"
    volumes:
      - /mnt/storj/logs:/mnt/storj/logs
      - ./appconfig/promtail:/config
      - /path/to/appdata/promtail:/data
    command: -config.file=/config/config.yml

  loki:
    image: grafana/loki:2.1.0
    ports:
      - "3100:3100"
    volumes:
      - "./appconfig/loki:/config"
      - /path/to/appdata/loki:/data
    command: -config.file=/config/local-config.yaml
    depends_on: 
      - promtail
